export const data= [
    {
        id: 1,
        name: "Beverly SpringField",
        rent: "2700",
        address:"2821 Lake Sevilla, Palm Harbor, TX",
        beds: "4",
        bathrooms:"2",
        area:"6x7.5",
        region:"New York USA",
        type: "House",
        lastMoveInDate: "2022-09-12",
      },

      {
        id: 2,
        name: "Palm Harbor",
        rent: "2095",
        address:"2699 Green Valley, Highland Lake, FL",
        beds: "3",
        bathrooms:"2",
        area:"5x7",
        region:"New Jersey USA",
        type: "House",
        lastMoveInDate: "2022-09-12",
      },

      {
        id: 3,
        name: "Faulkner Ave",
        rent: "4550",
        address:"909 Woodland St, Michigan, IN",
        beds: "4",
        bathrooms:"3",
        area:"8x10",
        region:"New York USA",
        type: "House",
        lastMoveInDate: "2022-09-19",
      },

      {
        id: 4,
        name: "Modern Heights",
        rent: "700",
        address:"mock address",
        beds: "4",
        bathrooms:"2",
        area:"6x7.5",
        region:"Delhi India",
        type: "Apartment",
        lastMoveInDate: "2022-09-19",
      },
];